In [9]:
import pandas as pd

meeting_note_csv_path = r"C:\LUNA\whisper\audio\Forward_Base_Taking_a_Day_Off_result_20261023_203825_944308\Forward_Base_Taking_a_Day_Off_by_Whisper_stt_Final.csv"
df_rttm = pd.read_csv(meeting_note_csv_path, encoding="utf-8-sig", keep_default_na=False)

# 여보, text가 빈칸이거나 공백만 있는 행을 이렇게 제외하면 돼.
df_rttm = df_rttm[
    df_rttm["text"].fillna("").str.strip().ne("")
].reset_index(drop=True)

# UNKNOWN 빼고 대사만
df_rttm = df_rttm.loc[
    ~df_rttm["speaker_id"].isin(["SPEAKER_00", "UNKNOWN"])
    & df_rttm["text"].fillna("").str.strip().ne("")
].reset_index(drop=True)

display(df_rttm)

,start,end,speaker_id,duration,text,status,review_word_count
0,80.609094,83.933469,SPEAKER_01,3.324,"잠깐 오빠, 그렇게 힘주면 안 돼.",assigned,1
1,84.456594,87.156594,SPEAKER_01,2.700,"좋아, 그렇게 더 부드럽게.",assigned,0
2,88.540344,92.455344,SPEAKER_01,3.915,"다리는 조금만 더 벌리고, 허리는 살짝만 풀어봐.",assigned,0
3,92.590344,95.189094,SPEAKER_01,2.599,나머지는 내가 알아서 할게.,assigned,0
4,99.255969,99.964719,SPEAKER_02,0.709,"루피,",assigned,0
5,101.145969,102.563469,SPEAKER_02,1.418,그냥 사이즈만 잰다며.,assigned,1
6,102.833469,103.575969,SPEAKER_02,0.742,얼른어나,assigned,0
7,108.520344,113.363469,SPEAKER_01,4.843,오빠가 가만히 있질 않는걸 그리고 사이즈 재는 건 네가 부탁한 거잖아,assigned,1
8,113.768469,117.970344,SPEAKER_01,4.202,같이 만찬에 가야 한다며 그럼 맞춤 정장이 필요할 테고 그래서 내가,assigned,1
9,117.970344,122.290344,SPEAKER_02,4.320,말했었지 그냥 적당히 괜찮은 수트 하나만 골라달라고,assigned,0
10,122.644719,127.943469,SPEAKER_02,5.299,왜 맞춤 제작까지 하려는? 비효율적이야. 가성비란 말이 괜히 있는 게 아니라고.,assigned,5
11,128.584719,146.269719,SPEAKER_01,17.685,"오빠, 어떻게 생각해? 난 오빠를 위해서 우리 가게도 통째로 비우고 이렇게 직접 사...",assigned,0
12,149.138469,151.467219,SPEAKER_01,2.329,역시 나랑 같은 생각이구나.,assigned,1
13,152.159094,155.145969,SPEAKER_01,2.987,"그럼, 사이즈를 한번 재볼까?",assigned,0
14,155.550969,160.545969,SPEAKER_01,4.995,"긴장하지 말고 웃어, 오빠. 누가 보면 높이가 잡아먹는 줄 알겠어.",assigned,0
15,165.186594,166.722219,SPEAKER_02,1.536,사이즈 재다가 날 새겠어!,assigned,0
16,168.814719,170.687844,SPEAKER_02,1.873,"백, 칠십오, 백십, 됐어!",assigned,0
17,173.691594,175.176594,SPEAKER_01,1.485,그렇게 대충 하면 안 돼!,assigned,1
18,175.497219,179.715969,SPEAKER_01,4.219,루피의 맞춤 제작법은 스물일곱 개의 칫솔을 다 재야 한다고!,assigned,0
19,180.610344,182.247219,SPEAKER_01,1.637,그러고 있을 시간이 없어!,assigned,0
20,182.584719,186.027219,SPEAKER_02,3.442,내 차 VIP 정비도 열다섯 항목이면 충분했다고!,assigned,0
21,187.900344,192.051594,SPEAKER_02,4.151,알지도 못하면서 레오�,assigned,0
22,204.150969,208.724094,SPEAKER_02,4.573,깔끔한 수트에 금태 안경이면 충분해,assigned,0
23,209.247219,211.373469,SPEAKER_02,2.126,"전문가 느낌, 확실하게 나잖아?",assigned,0
24,213.010344,213.533469,SPEAKER_02,0.523,안 돼!,assigned,0
25,214.090344,216.165969,SPEAKER_02,2.076,디자이너인 루피 말을 들어야 해!,assigned,0
26,216.537219,221.869719,SPEAKER_02,5.332,"이름만 파티지, 잠입해야 하는 작전인데 저렇게 눈에 띄게 입혀놓고는 어떻게 잠입하라...",assigned,0
27,227.944719,229.041594,SPEAKER_01,1.097,오빠...,assigned,1
28,229.210344,237.310344,SPEAKER_01,8.100,"사실 오빠가 다른 여자랑 파티를 가는 건데 루피가 옷을 만들어야 한다는 게 너무, ...",assigned,0
29,238.491594,238.980969,SPEAKER_01,0.489,뭐?,assigned,1
30,240.111594,245.039094,SPEAKER_01,4.927,오빠는 루피의 공식 남친이잖아. 내 방송 시청자들은 다 아는걸.,assigned,0
31,245.292219,246.962844,SPEAKER_01,1.671,"그러니까 나도,",assigned,0
32,246.962844,251.805969,SPEAKER_02,4.843,"나도 혹시... 고객님, 나랑의 임무가 먼저라는 걸 알아줘.",assigned,1
33,254.742219,259.163469,SPEAKER_01,4.421,정말? 임무 끝나면 루피랑 커플넉 입고 데이트 가주는 거지?,assigned,1
34,259.365969,260.361594,SPEAKER_01,0.996,약속이야?,assigned,0
35,264.900969,268.259094,SPEAKER_03,3.358,뭐꼬? 둘이 모여가 뭐하나 했더위만,assigned,0
36,268.731594,271.262844,SPEAKER_03,2.531,이런,assigned,0
37,276.595344,281.691594,SPEAKER_03,5.096,재밌는 거 알겠나?,assigned,1
38,283.176594,286.585344,SPEAKER_03,3.409,마침 우리 가게에 방어 소재가 세일 중이거든?,assigned,0
39,287.597844,289.538469,SPEAKER_03,1.941,우리 신참 옷에 쓸 거면...,assigned,0
40,290.500344,293.082219,SPEAKER_03,2.582,포인트 할인에 보너스까지 얹어줄게!,assigned,0
41,293.959719,295.545969,SPEAKER_03,1.586,어떤 노? 슬기타재?,assigned,0
42,297.300969,300.304719,SPEAKER_03,3.004,"물론, 신참이 결제한다 카면...",assigned,0
43,300.726594,303.477219,SPEAKER_03,2.751,다른 결제 방식도 얼마든지 환영이다.,assigned,0
44,304.945344,310.125969,SPEAKER_03,5.181,"아휴, 절대로 안 돼! 오빠한테 그런 철판 같은 옷 입히는 거! 난 반대야!",assigned,0
45,310.952844,312.927219,SPEAKER_03,1.974,예쁘기만 한 게 다는 아니라!,assigned,0
46,314.024094,321.432219,SPEAKER_03,7.408,"제 기능을 못하는 옷은 상품으로서 가치가 없데이! 신참, 잘 알고 있지? 내가 고른...",assigned,0
47,321.938469,323.642844,SPEAKER_02,1.704,이러고 있는 시간이 아까워.,assigned,0
48,327.439719,327.810969,SPEAKER_02,0.371,오빠는,assigned,1
49,327.810969,332.029719,SPEAKER_01,4.219,내 편이지! 루피가 디자이너니까 루피의 말을 들어야지!,assigned,5
50,332.620344,341.783469,SPEAKER_03,9.163,이 가스나가 뭐라카노! 실용성이 제일 중요하다! 이 디자인은 신첨을 위한 최적의 선...,assigned,0
51,342.205344,343.774719,SPEAKER_02,1.569,너희 둘은 빠져.,assigned,1
52,350.929719,353.612844,SPEAKER_03,2.683,"이것도,",assigned,0
53,361.915344,364.109094,SPEAKER_02,2.194,안경만 추가해줘.,assigned,0

In [10]:
name_dict = {
    "SPEAKER_01" : "루피",
    "SPEAKER_02" : "도라",
    "SPEAKER_03" : "얀",
}

df_rttm["name"] = df_rttm["speaker_id"].apply(lambda x: name_dict[x])

display(df_rttm);

,start,end,speaker_id,duration,text,status,review_word_count,name
0,80.609094,83.933469,SPEAKER_01,3.324,"잠깐 오빠, 그렇게 힘주면 안 돼.",assigned,1,루피
1,84.456594,87.156594,SPEAKER_01,2.700,"좋아, 그렇게 더 부드럽게.",assigned,0,루피
2,88.540344,92.455344,SPEAKER_01,3.915,"다리는 조금만 더 벌리고, 허리는 살짝만 풀어봐.",assigned,0,루피
3,92.590344,95.189094,SPEAKER_01,2.599,나머지는 내가 알아서 할게.,assigned,0,루피
4,99.255969,99.964719,SPEAKER_02,0.709,"루피,",assigned,0,도라
5,101.145969,102.563469,SPEAKER_02,1.418,그냥 사이즈만 잰다며.,assigned,1,도라
6,102.833469,103.575969,SPEAKER_02,0.742,얼른어나,assigned,0,도라
7,108.520344,113.363469,SPEAKER_01,4.843,오빠가 가만히 있질 않는걸 그리고 사이즈 재는 건 네가 부탁한 거잖아,assigned,1,루피
8,113.768469,117.970344,SPEAKER_01,4.202,같이 만찬에 가야 한다며 그럼 맞춤 정장이 필요할 테고 그래서 내가,assigned,1,루피
9,117.970344,122.290344,SPEAKER_02,4.320,말했었지 그냥 적당히 괜찮은 수트 하나만 골라달라고,assigned,0,도라
10,122.644719,127.943469,SPEAKER_02,5.299,왜 맞춤 제작까지 하려는? 비효율적이야. 가성비란 말이 괜히 있는 게 아니라고.,assigned,5,도라
11,128.584719,146.269719,SPEAKER_01,17.685,"오빠, 어떻게 생각해? 난 오빠를 위해서 우리 가게도 통째로 비우고 이렇게 직접 사...",assigned,0,루피
12,149.138469,151.467219,SPEAKER_01,2.329,역시 나랑 같은 생각이구나.,assigned,1,루피
13,152.159094,155.145969,SPEAKER_01,2.987,"그럼, 사이즈를 한번 재볼까?",assigned,0,루피
14,155.550969,160.545969,SPEAKER_01,4.995,"긴장하지 말고 웃어, 오빠. 누가 보면 높이가 잡아먹는 줄 알겠어.",assigned,0,루피
15,165.186594,166.722219,SPEAKER_02,1.536,사이즈 재다가 날 새겠어!,assigned,0,도라
16,168.814719,170.687844,SPEAKER_02,1.873,"백, 칠십오, 백십, 됐어!",assigned,0,도라
17,173.691594,175.176594,SPEAKER_01,1.485,그렇게 대충 하면 안 돼!,assigned,1,루피
18,175.497219,179.715969,SPEAKER_01,4.219,루피의 맞춤 제작법은 스물일곱 개의 칫솔을 다 재야 한다고!,assigned,0,루피
19,180.610344,182.247219,SPEAKER_01,1.637,그러고 있을 시간이 없어!,assigned,0,루피
20,182.584719,186.027219,SPEAKER_02,3.442,내 차 VIP 정비도 열다섯 항목이면 충분했다고!,assigned,0,도라
21,187.900344,192.051594,SPEAKER_02,4.151,알지도 못하면서 레오�,assigned,0,도라
22,204.150969,208.724094,SPEAKER_02,4.573,깔끔한 수트에 금태 안경이면 충분해,assigned,0,도라
23,209.247219,211.373469,SPEAKER_02,2.126,"전문가 느낌, 확실하게 나잖아?",assigned,0,도라
24,213.010344,213.533469,SPEAKER_02,0.523,안 돼!,assigned,0,도라
25,214.090344,216.165969,SPEAKER_02,2.076,디자이너인 루피 말을 들어야 해!,assigned,0,도라
26,216.537219,221.869719,SPEAKER_02,5.332,"이름만 파티지, 잠입해야 하는 작전인데 저렇게 눈에 띄게 입혀놓고는 어떻게 잠입하라...",assigned,0,도라
27,227.944719,229.041594,SPEAKER_01,1.097,오빠...,assigned,1,루피
28,229.210344,237.310344,SPEAKER_01,8.100,"사실 오빠가 다른 여자랑 파티를 가는 건데 루피가 옷을 만들어야 한다는 게 너무, ...",assigned,0,루피
29,238.491594,238.980969,SPEAKER_01,0.489,뭐?,assigned,1,루피
30,240.111594,245.039094,SPEAKER_01,4.927,오빠는 루피의 공식 남친이잖아. 내 방송 시청자들은 다 아는걸.,assigned,0,루피
31,245.292219,246.962844,SPEAKER_01,1.671,"그러니까 나도,",assigned,0,루피
32,246.962844,251.805969,SPEAKER_02,4.843,"나도 혹시... 고객님, 나랑의 임무가 먼저라는 걸 알아줘.",assigned,1,도라
33,254.742219,259.163469,SPEAKER_01,4.421,정말? 임무 끝나면 루피랑 커플넉 입고 데이트 가주는 거지?,assigned,1,루피
34,259.365969,260.361594,SPEAKER_01,0.996,약속이야?,assigned,0,루피
35,264.900969,268.259094,SPEAKER_03,3.358,뭐꼬? 둘이 모여가 뭐하나 했더위만,assigned,0,얀
36,268.731594,271.262844,SPEAKER_03,2.531,이런,assigned,0,얀
37,276.595344,281.691594,SPEAKER_03,5.096,재밌는 거 알겠나?,assigned,1,얀
38,283.176594,286.585344,SPEAKER_03,3.409,마침 우리 가게에 방어 소재가 세일 중이거든?,assigned,0,얀
39,287.597844,289.538469,SPEAKER_03,1.941,우리 신참 옷에 쓸 거면...,assigned,0,얀
40,290.500344,293.082219,SPEAKER_03,2.582,포인트 할인에 보너스까지 얹어줄게!,assigned,0,얀
41,293.959719,295.545969,SPEAKER_03,1.586,어떤 노? 슬기타재?,assigned,0,얀
42,297.300969,300.304719,SPEAKER_03,3.004,"물론, 신참이 결제한다 카면...",assigned,0,얀
43,300.726594,303.477219,SPEAKER_03,2.751,다른 결제 방식도 얼마든지 환영이다.,assigned,0,얀
44,304.945344,310.125969,SPEAKER_03,5.181,"아휴, 절대로 안 돼! 오빠한테 그런 철판 같은 옷 입히는 거! 난 반대야!",assigned,0,얀
45,310.952844,312.927219,SPEAKER_03,1.974,예쁘기만 한 게 다는 아니라!,assigned,0,얀
46,314.024094,321.432219,SPEAKER_03,7.408,"제 기능을 못하는 옷은 상품으로서 가치가 없데이! 신참, 잘 알고 있지? 내가 고른...",assigned,0,얀
47,321.938469,323.642844,SPEAKER_02,1.704,이러고 있는 시간이 아까워.,assigned,0,도라
48,327.439719,327.810969,SPEAKER_02,0.371,오빠는,assigned,1,도라
49,327.810969,332.029719,SPEAKER_01,4.219,내 편이지! 루피가 디자이너니까 루피의 말을 들어야지!,assigned,5,루피
50,332.620344,341.783469,SPEAKER_03,9.163,이 가스나가 뭐라카노! 실용성이 제일 중요하다! 이 디자인은 신첨을 위한 최적의 선...,assigned,0,얀
51,342.205344,343.774719,SPEAKER_02,1.569,너희 둘은 빠져.,assigned,1,도라
52,350.929719,353.612844,SPEAKER_03,2.683,"이것도,",assigned,0,얀
53,361.915344,364.109094,SPEAKER_02,2.194,안경만 추가해줘.,assigned,0,도라

In [11]:
# JSON 형식으로 변환
meeting_note_txt = df_rttm[['start', 'end', 'name', 'text']].to_json(orient='records',force_ascii=False)
print(meeting_note_txt)

[{"start":80.60909375,"end":83.93346875,"name":"루피","text":"잠깐 오빠, 그렇게 힘주면 안 돼."},{"start":84.45659375,"end":87.15659375,"name":"루피","text":"좋아, 그렇게 더 부드럽게."},{"start":88.54034375,"end":92.45534375,"name":"루피","text":"다리는 조금만 더 벌리고, 허리는 살짝만 풀어봐."},{"start":92.59034375,"end":95.18909375,"name":"루피","text":"나머지는 내가 알아서 할게."},{"start":99.25596875,"end":99.96471875,"name":"도라","text":"루피,"},{"start":101.14596875,"end":102.56346875,"name":"도라","text":"그냥 사이즈만 잰다며."},{"start":102.83346875,"end":103.57596875,"name":"도라","text":"얼른어나"},{"start":108.52034375,"end":113.36346875,"name":"루피","text":"오빠가 가만히 있질 않는걸 그리고 사이즈 재는 건 네가 부탁한 거잖아"},{"start":113.76846875,"end":117.97034375,"name":"루피","text":"같이 만찬에 가야 한다며 그럼 맞춤 정장이 필요할 테고 그래서 내가"},{"start":117.97034375,"end":122.29034375,"name":"도라","text":"말했었지 그냥 적당히 괜찮은 수트 하나만 골라달라고"},{"start":122.64471875,"end":127.94346875,"name":"도라","text":"왜 맞춤 제작까지 하려는? 비효율적이야. 가성비란 말이 괜히 있는 게 아니라고."},{"start":128.58471875,"end":146.26971875,"name":"루피","text":"오빠, 어떻게 생각해? 난 오빠를 위해서 우리 가게도 통째로 비우고 이렇게 직접 사이즈를 재주로 온 건데. 게다가 온 매장을 다 뒤져서 제일 좋은 원단만 싹 모아왔단 말이야. 그런데 저렇게 이야기하는 건 좀 너무하지 않아? 내 정성을 무시하는 발언이라고."},{"start":149.13846875,"end":151.46721875,"name":"루피","text":"역시 나랑 같은 생각이구나."},{"start":152.15909375,"end":155.14596875,"name":"루피","text":"그럼, 사이즈를 한번 재볼까?"},{"start":155.55096875,"end":160.54596875,"name":"루피","text":"긴장하지 말고 웃어, 오빠. 누가 보면 높이가 잡아먹는 줄 알겠어."},{"start":165.18659375,"end":166.72221875,"name":"도라","text":"사이즈 재다가 날 새겠어!"},{"start":168.81471875,"end":170.68784375,"name":"도라","text":"백, 칠십오, 백십, 됐어!"},{"start":173.69159375,"end":175.17659375,"name":"루피","text":"그렇게 대충 하면 안 돼!"},{"start":175.49721875,"end":179.71596875,"name":"루피","text":"루피의 맞춤 제작법은 스물일곱 개의 칫솔을 다 재야 한다고!"},{"start":180.61034375,"end":182.24721875,"name":"루피","text":"그러고 있을 시간이 없어!"},{"start":182.58471875,"end":186.02721875,"name":"도라","text":"내 차 VIP 정비도 열다섯 항목이면 충분했다고!"},{"start":187.90034375,"end":192.05159375,"name":"도라","text":"알지도 못하면서 레오�"},{"start":204.15096875,"end":208.72409375,"name":"도라","text":"깔끔한 수트에 금태 안경이면 충분해"},{"start":209.24721875,"end":211.37346875,"name":"도라","text":"전문가 느낌, 확실하게 나잖아?"},{"start":213.01034375,"end":213.53346875,"name":"도라","text":"안 돼!"},{"start":214.09034375,"end":216.16596875,"name":"도라","text":"디자이너인 루피 말을 들어야 해!"},{"start":216.53721875,"end":221.86971875,"name":"도라","text":"이름만 파티지, 잠입해야 하는 작전인데 저렇게 눈에 띄게 입혀놓고는 어떻게 잠입하라는 거야?"},{"start":227.94471875,"end":229.04159375,"name":"루피","text":"오빠..."},{"start":229.21034375,"end":237.31034375,"name":"루피","text":"사실 오빠가 다른 여자랑 파티를 가는 건데 루피가 옷을 만들어야 한다는 게 너무, 너무 속상해서 그래"},{"start":238.49159375,"end":238.98096875,"name":"루피","text":"뭐?"},{"start":240.11159375,"end":245.03909375,"name":"루피","text":"오빠는 루피의 공식 남친이잖아. 내 방송 시청자들은 다 아는걸."},{"start":245.29221875,"end":246.96284375,"name":"루피","text":"그러니까 나도,"},{"start":246.96284375,"end":251.80596875,"name":"도라","text":"나도 혹시... 고객님, 나랑의 임무가 먼저라는 걸 알아줘."},{"start":254.74221875,"end":259.16346875,"name":"루피","text":"정말? 임무 끝나면 루피랑 커플넉 입고 데이트 가주는 거지?"},{"start":259.36596875,"end":260.36159375,"name":"루피","text":"약속이야?"},{"start":264.90096875,"end":268.25909375,"name":"얀","text":"뭐꼬? 둘이 모여가 뭐하나 했더위만"},{"start":268.73159375,"end":271.26284375,"name":"얀","text":"이런"},{"start":276.59534375,"end":281.69159375,"name":"얀","text":"재밌는 거 알겠나?"},{"start":283.17659375,"end":286.58534375,"name":"얀","text":"마침 우리 가게에 방어 소재가 세일 중이거든?"},{"start":287.59784375,"end":289.53846875,"name":"얀","text":"우리 신참 옷에 쓸 거면..."},{"start":290.50034375,"end":293.08221875,"name":"얀","text":"포인트 할인에 보너스까지 얹어줄게!"},{"start":293.95971875,"end":295.54596875,"name":"얀","text":"어떤 노? 슬기타재?"},{"start":297.30096875,"end":300.30471875,"name":"얀","text":"물론, 신참이 결제한다 카면..."},{"start":300.72659375,"end":303.47721875,"name":"얀","text":"다른 결제 방식도 얼마든지 환영이다."},{"start":304.94534375,"end":310.12596875,"name":"얀","text":"아휴, 절대로 안 돼! 오빠한테 그런 철판 같은 옷 입히는 거! 난 반대야!"},{"start":310.95284375,"end":312.92721875,"name":"얀","text":"예쁘기만 한 게 다는 아니라!"},{"start":314.02409375,"end":321.43221875,"name":"얀","text":"제 기능을 못하는 옷은 상품으로서 가치가 없데이! 신참, 잘 알고 있지? 내가 고른 옷으로도 충분해!"},{"start":321.93846875,"end":323.64284375,"name":"도라","text":"이러고 있는 시간이 아까워."},{"start":327.43971875,"end":327.81096875,"name":"도라","text":"오빠는"},{"start":327.81096875,"end":332.02971875,"name":"루피","text":"내 편이지! 루피가 디자이너니까 루피의 말을 들어야지!"},{"start":332.62034375,"end":341.78346875,"name":"얀","text":"이 가스나가 뭐라카노! 실용성이 제일 중요하다! 이 디자인은 신첨을 위한 최적의 선택이라니까! 이건 나와 고객님의 작전이야!"},{"start":342.20534375,"end":343.77471875,"name":"도라","text":"너희 둘은 빠져."},{"start":350.92971875,"end":353.61284375,"name":"얀","text":"이것도,"},{"start":361.91534375,"end":364.10909375,"name":"도라","text":"안경만 추가해줘."}]

In [12]:
system_prompt = f'''
너는 회의 내용을 요약하는 봇이다. 아래 회의록을 읽고, 주요 내용을 요약하라.
결과는 마크다운 형식으로 작성한다.

# 회의 제목

## 주요 내용

## 참석자별 입장

## 결정 사항

=============== 이하 회의록 ===============
{meeting_note_txt}
'''

In [13]:
import os

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
api_key = os.getenv('OPEN_API_KEY')
client = OpenAI(api_key=api_key)

In [14]:
response = client.chat.completions.create(
    model="gpt-6-luna",
    messages=[
        {"role": "system", "content": system_prompt},
    ]
)

summary = response.choices[0].message.content
summary = summary.strip();

print(summary)

# 침투 작전용 정장 제작 논의

## 주요 내용
- 만찬을 가장한 잠입 작전에 입을 옷을 두고 맞춤 정장 제작 여부와 디자인을 논의했다.
- 루피는 직접 치수를 재고 좋은 원단을 준비해 맞춤 정장을 만들려 했지만, 도라는 시간과 비용을 고려해 적당한 기성복이면 충분하다고 주장했다.
- 의상 논의 중 루피는 도라가 다른 여성과 파티에 가는 것이 속상하다고 털어놓았다. 도라는 임무가 우선임을 강조했고, 루피는 임무 후 데이트 약속을 받아냈다.
- 얀도 옷 선택에 끼어들어 실용성을 강조하며 자신이 고른 옷을 추천했다.

## 참석자별 입장
- **루피:** 정성을 담은 맞춤 정장을 만들고 싶어 한다. 디자이너로서 자신의 의견을 따르길 바라며, 도라가 다른 여성과 파티에 가는 것을 질투한다.
- **도라:** 맞춤 제작은 비효율적이라고 보고, 잠입 임무에 적합한 단정하고 눈에 띄지 않는 옷을 원한다. 임무가 개인적인 약속보다 우선이라고 강조한다.
- **얀:** 보기 좋은 것보다 기능과 실용성이 중요하다고 주장하며 자신이 고른 옷을 권한다. 원단 할인도 제안한다.

## 결정 사항
- 복장 선택이 완전히 확정되지는 않았으나, 도라는 마지막에 **안경만 추가하자**고 했다.
- 루피는 임무가 끝난 뒤 커플 옷을 입고 데이트하자는 약속을 받았다.

In [15]:
with open('./summary.md', 'w', encoding="utf-8") as f:
    f.write(summary)

In [16]:
df_meeting_note = df_rttm[['start', 'end', 'name', 'text']].copy();
df_meeting_note.dropna(inplace=True)

meeting_note_dict = df_meeting_note.to_dict(orient='records') # 딕셔너리 형태로 변환
meeting_note_dict

[{'start': 80.60909375,
  'end': 83.93346875,
  'name': '루피',
  'text': '잠깐 오빠, 그렇게 힘주면 안 돼.'},
 {'start': 84.45659375000001,
  'end': 87.15659375,
  'name': '루피',
  'text': '좋아, 그렇게 더 부드럽게.'},
 {'start': 88.54034375,
  'end': 92.45534375,
  'name': '루피',
  'text': '다리는 조금만 더 벌리고, 허리는 살짝만 풀어봐.'},
 {'start': 92.59034375,
  'end': 95.18909375,
  'name': '루피',
  'text': '나머지는 내가 알아서 할게.'},
 {'start': 99.25596875, 'end': 99.96471875, 'name': '도라', 'text': '루피,'},
 {'start': 101.14596875,
  'end': 102.56346875,
  'name': '도라',
  'text': '그냥 사이즈만 잰다며.'},
 {'start': 102.83346875, 'end': 103.57596875, 'name': '도라', 'text': '얼른어나'},
 {'start': 108.52034375,
  'end': 113.36346875,
  'name': '루피',
  'text': '오빠가 가만히 있질 않는걸 그리고 사이즈 재는 건 네가 부탁한 거잖아'},
 {'start': 113.76846875,
  'end': 117.97034375,
  'name': '루피',
  'text': '같이 만찬에 가야 한다며 그럼 맞춤 정장이 필요할 테고 그래서 내가'},
 {'start': 117.97034375,
  'end': 122.29034375,
  'name': '도라',
  'text': '말했었지 그냥 적당히 괜찮은 수트 하나만 골라달라고'},
 {'start': 122.64471875,
  'end': 127.94346875,
  'name': '도라',
  'text': '왜 맞춤 제작까지 하려는? 비효율적이야. 가성비란 말이 괜히 있는 게 아니라고.'},
 {'start': 128.58471875,
  'end': 146.26971875,
  'name': '루피',
  'text': '오빠, 어떻게 생각해? 난 오빠를 위해서 우리 가게도 통째로 비우고 이렇게 직접 사이즈를 재주로 온 건데. 게다가 온 매장을 다 뒤져서 제일 좋은 원단만 싹 모아왔단 말이야. 그런데 저렇게 이야기하는 건 좀 너무하지 않아? 내 정성을 무시하는 발언이라고.'},
 {'start': 149.13846875000002,
  'end': 151.46721875,
  'name': '루피',
  'text': '역시 나랑 같은 생각이구나.'},
 {'start': 152.15909375,
  'end': 155.14596875,
  'name': '루피',
  'text': '그럼, 사이즈를 한번 재볼까?'},
 {'start': 155.55096875,
  'end': 160.54596875,
  'name': '루피',
  'text': '긴장하지 말고 웃어, 오빠. 누가 보면 높이가 잡아먹는 줄 알겠어.'},
 {'start': 165.18659375,
  'end': 166.72221875000002,
  'name': '도라',
  'text': '사이즈 재다가 날 새겠어!'},
 {'start': 168.81471875,
  'end': 170.68784375,
  'name': '도라',
  'text': '백, 칠십오, 백십, 됐어!'},
 {'start': 173.69159375,
  'end': 175.17659375000002,
  'name': '루피',
  'text': '그렇게 대충 하면 안 돼!'},
 {'start': 175.49721875,
  'end': 179.71596875,
  'name': '루피',
  'text': '루피의 맞춤 제작법은 스물일곱 개의 칫솔을 다 재야 한다고!'},
 {'start': 180.61034375,
  'end': 182.24721875,
  'name': '루피',
  'text': '그러고 있을 시간이 없어!'},
 {'start': 182.58471875,
  'end': 186.02721875,
  'name': '도라',
  'text': '내 차 VIP 정비도 열다섯 항목이면 충분했다고!'},
 {'start': 187.90034375,
  'end': 192.05159375,
  'name': '도라',
  'text': '알지도 못하면서 레오�'},
 {'start': 204.15096875,
  'end': 208.72409375,
  'name': '도라',
  'text': '깔끔한 수트에 금태 안경이면 충분해'},
 {'start': 209.24721875,
  'end': 211.37346875,
  'name': '도라',
  'text': '전문가 느낌, 확실하게 나잖아?'},
 {'start': 213.01034375,
  'end': 213.53346875000005,
  'name': '도라',
  'text': '안 돼!'},
 {'start': 214.09034375,
  'end': 216.16596875,
  'name': '도라',
  'text': '디자이너인 루피 말을 들어야 해!'},
 {'start': 216.53721875,
  'end': 221.86971875,
  'name': '도라',
  'text': '이름만 파티지, 잠입해야 하는 작전인데 저렇게 눈에 띄게 입혀놓고는 어떻게 잠입하라는 거야?'},
 {'start': 227.94471875, 'end': 229.04159375, 'name': '루피', 'text': '오빠...'},
 {'start': 229.21034375,
  'end': 237.31034375,
  'name': '루피',
  'text': '사실 오빠가 다른 여자랑 파티를 가는 건데 루피가 옷을 만들어야 한다는 게 너무, 너무 속상해서 그래'},
 {'start': 238.49159375, 'end': 238.98096875, 'name': '루피', 'text': '뭐?'},
 {'start': 240.11159375000005,
  'end': 245.03909375,
  'name': '루피',
  'text': '오빠는 루피의 공식 남친이잖아. 내 방송 시청자들은 다 아는걸.'},
 {'start': 245.29221875,
  'end': 246.96284375,
  'name': '루피',
  'text': '그러니까 나도,'},
 {'start': 246.96284375,
  'end': 251.80596875,
  'name': '도라',
  'text': '나도 혹시... 고객님, 나랑의 임무가 먼저라는 걸 알아줘.'},
 {'start': 254.74221875,
  'end': 259.16346875,
  'name': '루피',
  'text': '정말? 임무 끝나면 루피랑 커플넉 입고 데이트 가주는 거지?'},
 {'start': 259.36596875000004,
  'end': 260.36159375,
  'name': '루피',
  'text': '약속이야?'},
 {'start': 264.90096875,
  'end': 268.25909375000003,
  'name': '얀',
  'text': '뭐꼬? 둘이 모여가 뭐하나 했더위만'},
 {'start': 268.73159375, 'end': 271.26284375, 'name': '얀', 'text': '이런'},
 {'start': 276.59534375000004,
  'end': 281.69159375000004,
  'name': '얀',
  'text': '재밌는 거 알겠나?'},
 {'start': 283.17659375,
  'end': 286.58534375,
  'name': '얀',
  'text': '마침 우리 가게에 방어 소재가 세일 중이거든?'},
 {'start': 287.59784375000004,
  'end': 289.53846875,
  'name': '얀',
  'text': '우리 신참 옷에 쓸 거면...'},
 {'start': 290.50034375,
  'end': 293.08221875000004,
  'name': '얀',
  'text': '포인트 할인에 보너스까지 얹어줄게!'},
 {'start': 293.95971875000004,
  'end': 295.54596875000004,
  'name': '얀',
  'text': '어떤 노? 슬기타재?'},
 {'start': 297.30096875000004,
  'end': 300.30471875,
  'name': '얀',
  'text': '물론, 신참이 결제한다 카면...'},
 {'start': 300.72659375,
  'end': 303.47721875,
  'name': '얀',
  'text': '다른 결제 방식도 얼마든지 환영이다.'},
 {'start': 304.94534375,
  'end': 310.12596875,
  'name': '얀',
  'text': '아휴, 절대로 안 돼! 오빠한테 그런 철판 같은 옷 입히는 거! 난 반대야!'},
 {'start': 310.95284375,
  'end': 312.92721875,
  'name': '얀',
  'text': '예쁘기만 한 게 다는 아니라!'},
 {'start': 314.02409375,
  'end': 321.43221875,
  'name': '얀',
  'text': '제 기능을 못하는 옷은 상품으로서 가치가 없데이! 신참, 잘 알고 있지? 내가 고른 옷으로도 충분해!'},
 {'start': 321.93846875,
  'end': 323.64284375,
  'name': '도라',
  'text': '이러고 있는 시간이 아까워.'},
 {'start': 327.43971875,
  'end': 327.81096875000003,
  'name': '도라',
  'text': '오빠는'},
 {'start': 327.81096875000003,
  'end': 332.02971875000003,
  'name': '루피',
  'text': '내 편이지! 루피가 디자이너니까 루피의 말을 들어야지!'},
 {'start': 332.62034375,
  'end': 341.78346875,
  'name': '얀',
  'text': '이 가스나가 뭐라카노! 실용성이 제일 중요하다! 이 디자인은 신첨을 위한 최적의 선택이라니까! 이건 나와 고객님의 작전이야!'},
 {'start': 342.20534375,
  'end': 343.77471875000003,
  'name': '도라',
  'text': '너희 둘은 빠져.'},
 {'start': 350.92971875, 'end': 353.61284375, 'name': '얀', 'text': '이것도,'},
 {'start': 361.91534375,
  'end': 364.10909375,
  'name': '도라',
  'text': '안경만 추가해줘.'}]

In [18]:
# GPT 보정

for row in meeting_note_dict:
    if not isinstance(row['text'], str): # 텍스트가 아닌 다른 형식인 경우 통과
        continue

    correction_system_prompt = f'''
        너는 주어진 회의 녹취록을 수정 및 보완하는 봇이다.
        주어진 회의 녹취록은 STT로 작성된 결과이므로, 이 중에 오류가 있는 부분을 찾아내고 수정하라.

        표현, 말투는 최대한 원본과 일치하도록 유지하되, 잘못 받아적은 내용을 수정하라.
        원본의 내용을 최대한 살리되, 잘못된 내용만 수정하라.
        어떤 경우에는 A라는 사람이 말한 내용을 B가 말한 것으로 잘못 기록된 경우도 있을 수 있다. 이런 경우에는 문맥을 고려하여 수정하라.

        원본 내용 중 빠지거나, 추가되거나, 잘못 기록된 부분을 찾아내어 수정하라. 수정된 메시지 이외에는 아무것도 작성하지 말라.
        --------------------------------
        회의 요약문 : {summary}
        --------------------------------
        회의 녹취록 전문: {df_meeting_note.to_json(orient='records', force_ascii=False)}
        --------------------------------
        확인할 메시지 원본: {row['text']}
    '''

    response = client.chat.completions.create(
        model="gpt-6-luna",
            messages=[
                {"role": "system", "content": correction_system_prompt},
            ]
    )

    correction = response.choices[0].message.content
    if ':' in correction: # “수정: “ 과 같은 형식으로 반환되는 경우 해결
        correction = correction.split(':')[-1]

    correction = correction.strip() # 좌우 공백 제거

    print(row['name'])
    print(row['text'])
    print(correction)
    print('--------------------')

    row['corrected_text'] = correction

루피
잠깐 오빠, 그렇게 힘주면 안 돼.
잠깐, 오빠. 그렇게 힘주면 안 돼.
--------------------
루피
좋아, 그렇게 더 부드럽게.
좋아, 그렇게 더 부드럽게.
--------------------
루피
다리는 조금만 더 벌리고, 허리는 살짝만 풀어봐.
다리는 조금만 더 벌리고, 허리는 살짝만 풀어봐.
--------------------
루피
나머지는 내가 알아서 할게.
나머지는 내가 알아서 할게.
--------------------
도라
루피,
루피,
--------------------
도라
그냥 사이즈만 잰다며.
그냥 사이즈만 잰다며.
--------------------
도라
얼른어나
얼른 해.
--------------------
루피
오빠가 가만히 있질 않는걸 그리고 사이즈 재는 건 네가 부탁한 거잖아
오빠가 가만히 있질 않는걸. 그리고 사이즈 재는 건 네가 부탁한 거잖아.
--------------------
루피
같이 만찬에 가야 한다며 그럼 맞춤 정장이 필요할 테고 그래서 내가
같이 만찬에 가야 한다며. 그럼 맞춤 정장이 필요할 테고, 그래서 내가…
--------------------
도라
말했었지 그냥 적당히 괜찮은 수트 하나만 골라달라고
말했었지. 그냥 적당히 괜찮은 수트 하나만 골라 달라고.
--------------------
도라
왜 맞춤 제작까지 하려는? 비효율적이야. 가성비란 말이 괜히 있는 게 아니라고.
왜 맞춤 제작까지 하려는 거야? 비효율적이야. 가성비란 말이 괜히 있는 게 아니라고.
--------------------
루피
오빠, 어떻게 생각해? 난 오빠를 위해서 우리 가게도 통째로 비우고 이렇게 직접 사이즈를 재주로 온 건데. 게다가 온 매장을 다 뒤져서 제일 좋은 원단만 싹 모아왔단 말이야. 그런데 저렇게 이야기하는 건 좀 너무하지 않아? 내 정성을 무시하는 발언이라고.
오빠, 어떻게 생각해? 난 오빠를 위해서 우리 가게도 통째로 비우고 이렇게 직접 사이즈를 재러 온 건데. 게다가 온 매장을 다 뒤져서 제일 좋은 원단만 싹 모아왔단 말이야. 그런데 저렇게 이야기하는 건 좀 너무하지 않아? 내 정성을 무시하는 발언이라고.
--------------------
루피
역시 나랑 같은 생각이구나.
역시 나랑 같은 생각이구나.
--------------------
루피
그럼, 사이즈를 한번 재볼까?
그럼, 사이즈를 한번 재볼까?
--------------------
루피
긴장하지 말고 웃어, 오빠. 누가 보면 높이가 잡아먹는 줄 알겠어.
긴장하지 말고 웃어, 오빠. 누가 보면 호랑이가 잡아먹는 줄 알겠어.
--------------------
도라
사이즈 재다가 날 새겠어!
사이즈 재다가 날 새겠어!
--------------------
도라
백, 칠십오, 백십, 됐어!
백, 칠십오, 백십, 됐어!
--------------------
루피
그렇게 대충 하면 안 돼!
그렇게 대충 하면 안 돼!
--------------------
루피
루피의 맞춤 제작법은 스물일곱 개의 칫솔을 다 재야 한다고!
루피의 맞춤 제작법은 스물일곱 개의 치수를 다 재야 한다고!
--------------------
루피
그러고 있을 시간이 없어!
그러고 있을 시간이 없어!
--------------------
도라
내 차 VIP 정비도 열다섯 항목이면 충분했다고!
내 차 VIP 정비도 열다섯 항목이면 충분했다고!
--------------------
도라
알지도 못하면서 레오�
알지도 못하면서!
--------------------
도라
깔끔한 수트에 금태 안경이면 충분해
깔끔한 수트에 금테 안경이면 충분해.
--------------------
도라
전문가 느낌, 확실하게 나잖아?
전문가 느낌, 확실하게 나잖아?
--------------------
도라
안 돼!
안 돼!
--------------------
도라
디자이너인 루피 말을 들어야 해!
디자이너인 루피 말을 들어야 해!
--------------------
도라
이름만 파티지, 잠입해야 하는 작전인데 저렇게 눈에 띄게 입혀놓고는 어떻게 잠입하라는 거야?
이름만 파티지, 잠입해야 하는 작전인데 저렇게 눈에 띄게 입혀놓고는 어떻게 잠입하라는 거야?
--------------------
루피
오빠...
오빠...
--------------------
루피
사실 오빠가 다른 여자랑 파티를 가는 건데 루피가 옷을 만들어야 한다는 게 너무, 너무 속상해서 그래
사실 오빠가 다른 여자랑 파티를 가는 건데 루피가 옷을 만들어야 한다는 게 너무, 너무 속상해서 그래.
--------------------
루피
뭐?
뭐?
--------------------
루피
오빠는 루피의 공식 남친이잖아. 내 방송 시청자들은 다 아는걸.
오빠는 루피의 공식 남친이잖아. 내 방송 시청자들은 다 아는걸.
--------------------
루피
그러니까 나도,
그러니까 나도...
--------------------
도라
나도 혹시... 고객님, 나랑의 임무가 먼저라는 걸 알아줘.
나도 혹시… 고객님, 나랑의 임무가 먼저라는 걸 알아줘.
--------------------
루피
정말? 임무 끝나면 루피랑 커플넉 입고 데이트 가주는 거지?
정말? 임무 끝나면 루피랑 커플룩 입고 데이트 가주는 거지?
--------------------
루피
약속이야?
약속이야?
--------------------
얀
뭐꼬? 둘이 모여가 뭐하나 했더위만
뭐꼬? 둘이 모여가 뭐 하나 했더니만.
--------------------
얀
이런
이런 재밌는 거 하고 있었나?
--------------------
얀
재밌는 거 알겠나?
재밌는 거 하고 있나?
--------------------
얀
마침 우리 가게에 방어 소재가 세일 중이거든?
마침 우리 가게에 방탄 소재가 세일 중이거든?
--------------------
얀
우리 신참 옷에 쓸 거면...
우리 신참 옷에 쓸 거면...
--------------------
얀
포인트 할인에 보너스까지 얹어줄게!
포인트 할인에 보너스까지 얹어줄게!
--------------------
얀
어떤 노? 슬기타재?
어떤 거? 수트까지?
--------------------
얀
물론, 신참이 결제한다 카면...
물론, 신참이 결제한다 카면...
--------------------
얀
다른 결제 방식도 얼마든지 환영이다.
다른 결제 방식도 얼마든지 환영이다.
--------------------
얀
아휴, 절대로 안 돼! 오빠한테 그런 철판 같은 옷 입히는 거! 난 반대야!
아휴, 절대로 안 돼! 오빠한테 그런 철판 같은 옷 입히는 거! 난 반대야!
--------------------
얀
예쁘기만 한 게 다는 아니라!
예쁘기만 한 게 다는 아이라!
--------------------
얀
제 기능을 못하는 옷은 상품으로서 가치가 없데이! 신참, 잘 알고 있지? 내가 고른 옷으로도 충분해!
제 기능을 못하는 옷은 상품으로서 가치가 없데이! 신참, 잘 알고 있지? 내가 고른 옷으로도 충분해!
--------------------
도라
이러고 있는 시간이 아까워.
이러고 있는 시간이 아까워.
--------------------
도라
오빠는
오빠는…
--------------------
루피
내 편이지! 루피가 디자이너니까 루피의 말을 들어야지!
내 편이지! 루피가 디자이너니까 루피의 말을 들어야지!
--------------------
얀
이 가스나가 뭐라카노! 실용성이 제일 중요하다! 이 디자인은 신첨을 위한 최적의 선택이라니까! 이건 나와 고객님의 작전이야!
이 가스나가 뭐라카노! 실용성이 제일 중요하다! 이 디자인은 신참을 위한 최적의 선택이라니까! 이건 나와 고객님의 작전이야!
--------------------
도라
너희 둘은 빠져.
너희 둘은 빠져.
--------------------
얀
이것도,
이것도.
--------------------
도라
안경만 추가해줘.
안경만 추가해줘.
--------------------

In [ ]:
# json 파일로 저장
import json

with open('./Forward_Base_Taking_a_Day_Off.json', 'w', encoding="utf-8") as f:
    json.dump(meeting_note_dict, f, ensure_ascii=False, indent=4)

In [ ]:
md_template = ""
for row in meeting_note_dict:
    md_template += f"- **{row['name']}** : {row['corrected_text']}\n"

with open('./Forward_Base_Taking_a_Day_Off.md', 'w', encoding='utf-8') as f:
    f.write(md_template)

In [ ]:
%pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Collecting lxml>=3.1.0 (from python-docx)
  Downloading lxml-6.1.3-cp312-cp312-win_amd64.whl.metadata (3.4 kB)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\LUNA\venv\Lib\site-packages (from python-docx) (4.16.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
Downloading lxml-6.1.3-cp312-cp312-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 4.0/4.0 MB 59.4 MB/s  0:00:00
Installing collected packages: lxml, python-docx

   -------------------- ------------------- 1/2 [python-docx]
   -------------------- ------------------- 1/2 [python-docx]
   ---------------------------------------- 2/2 [python-docx]

Successfully installed lxml-6.1.3 python-docx-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [ ]:
from docx import Document

document = Document()   # (1)  docx 객체 생성
document.add_heading('회의록', level=1) # (2) 제목 추가

table = document.add_table(rows=1, cols=2) # (3) 테이블 생성
table.style = 'Table Grid' # (4) 테이블 스타일 지정

hdr_cells = table.rows[0].cells # (5) 첫 번째 행에 셀 추가
hdr_cells[0].text = 'Speaker' # (6) 첫 번째 셀에 Speaker 추가
hdr_cells[1].text = 'Content'   # (7) 두 번째 셀에 Content 추가

# (8) 수정된 녹취록 파일을 읽어들여서 테이블에 추가
for row in meeting_note_dict:
    row_cells = table.add_row().cells
    row_cells[0].text = row['name']
    row_cells[1].text = row['corrected_text']

document.save('./Forward_Base_Taking_a_Day_Off.docx') # (9) docx 파일 저장